# Generated by Django 2.1.1 on 2019-03-13 20:07

from django.db import migrations, models
import django.db.models.deletion
import incidente.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calzado', '0001_initial'),
        ('persona', '0002_auto_20190311_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuerpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Distintivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calzado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calzado.Calzado')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado', models.CharField(max_length=10)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.Incidente')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidente.Cuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='ParteFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to=incidente.models.direc)),
                ('id_distintivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.Distintivo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDistintivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidente.TipoIncidente'),
        ),
        migrations.AddField(
            model_name='distintivo',
            name='id_parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.Parte'),
        ),
        migrations.AddField(
            model_name='distintivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidente.TipoDistintivo'),
        ),
    ]
