# Generated by Django 2.1.1 on 2019-03-14 19:57

from django.db import migrations, models
import django.db.models.deletion
import incidente.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calzado', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuerpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calzado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calzado.Calzado')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado', models.CharField(max_length=10)),
                ('detalle', models.CharField(max_length=100, null=True)),
                ('foto', models.FileField(upload_to=incidente.models.direc)),
                ('incidente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.Incidente')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidente.Cuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDistintivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='parte',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidente.TipoDistintivo'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidente.TipoIncidente'),
        ),
    ]
