# Generated by Django 2.1.1 on 2019-03-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distintivo',
            old_name='id_parte',
            new_name='parte_id',
        ),
        migrations.RenameField(
            model_name='incidente',
            old_name='calzado',
            new_name='calzado_id',
        ),
        migrations.RenameField(
            model_name='incidente',
            old_name='persona',
            new_name='persona_id',
        ),
        migrations.RenameField(
            model_name='incidente',
            old_name='tipo',
            new_name='tipo_id',
        ),
        migrations.RenameField(
            model_name='parte',
            old_name='incidente',
            new_name='incidente_id',
        ),
        migrations.RenameField(
            model_name='partefoto',
            old_name='id_distintivo',
            new_name='distintivo_id',
        ),
    ]
