# Generated by Django 2.1.1 on 2019-03-11 23:53

import calzado.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calzado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('motivo', models.FileField(upload_to=calzado.models.DirForma)),
            ],
        ),
        migrations.CreateModel(
            name='FotoCalzado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente', models.FileField(upload_to=calzado.models.DirCalzado)),
                ('izquierda', models.FileField(upload_to=calzado.models.DirCalzado)),
                ('atras', models.FileField(upload_to=calzado.models.DirCalzado)),
                ('derecha', models.FileField(upload_to=calzado.models.DirCalzado)),
                ('inferior', models.FileField(upload_to=calzado.models.DirCalzado)),
                ('calzado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='calzado.Calzado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='calzado',
            name='forma_inf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='forma_inf', to='calzado.Forma'),
        ),
        migrations.AddField(
            model_name='calzado',
            name='forma_sup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='forma_sup', to='calzado.Forma'),
        ),
        migrations.AddField(
            model_name='calzado',
            name='marca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='calzado.Marca'),
        ),
    ]
